"""add payment models

Revision ID: 7bfdb7165e67
Revises: 5f595d52d612
Create Date: 2022-01-16 17:56:39.438828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfdb7165e67'
down_revision = '5f595d52d612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'payment',
        sa.Column('created_at', sa.DateTime(), default=sa.text('now()'), nullable=True),
        sa.Column('edited_at', sa.DateTime(), onupdate=sa.text('now()'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment', sa.String(), nullable=True),
        sa.Column('price', sa.Integer(), nullable=False),
        sa.Column('edited', sa.Boolean(), nullable=True, default=False),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'comment',
        sa.Column('created_at', sa.DateTime(), default=sa.text('now()'), nullable=True),
        sa.Column('edited_at', sa.DateTime(), onupdate=sa.text('now()'), nullable=True),
        sa.Column('id', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('edited', sa.Boolean(), nullable=True, default=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('payment')
    op.drop_table('category')
    # ### end Alembic commands ###
