name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      run: pipx install poetry
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - name: Get file changes
      id: get_file_changes
      uses: tj-actions/changed-files@v18.7
      with:
        separator: " "
        files: "**/*.py"
    - name: Install dependencies
      run: |
        cd backend/app
        poetry install
    - name: Analysing the code with pylint
      run: |
        cd backend/app
        poetry run pylint --rcfile=.pylintrc $(git ls-files '*.py')
