name: Pylint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get file changes
      id: get_file_changes
      uses: tj-actions/changed-files@v18.7
      with:
        separator: ' '
        files: |
          *.py
          **/*.py
    - name: test
      run: |
        echo '${{ steps.get_file_changes.outputs.all_changed_files }}'
        echo '${{ steps.get_file_changes.outputs.any_changed }}'
    - name: Install dependencies
      if: steps.get_file_changes.outputs.any_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      if: steps.get_file_changes.outputs.any_changed == 'true'
      run: |
        pylint ${{ steps.get_file_changes.outputs.all_changed_files }}
