name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - name: Get file changes
      id: get_file_changes
      uses: tj-actions/changed-files@v18.7
      with:
        separator: " "
        files: "**/*.py"
    - name: Switch python version for poetry
      run: |
        cd backend/app
        poetry env use python${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python --version
        python3 --version
        cd backend/app
        poetry env list
        poetry install
    - name: Analysing the code with pylint
      run: |
        cd backend/app
        poetry run pylint --rcfile=.pylintrc $(git ls-files '*.py')
