name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Get file changes
      id: get_changed_files
      uses: tj-actions/changed-files@v18.7
      with:
        separator: " "
        files: "**/*.py"
    - name: Set up Python ${{ matrix.python-version }}
      if: steps.get_changed_files.outputs.any_changed == 'true'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      if: steps.get_changed_files.outputs.any_changed == 'true'
      uses: snok/install-poetry@v1.0.0
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      if: steps.get_changed_files.outputs.any_changed == 'true'
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.get_changed_files.outputs.any_changed == 'true'
      run: |
        cd backend/app
        poetry install --no-root
    - name: Analysing the code with pylint
      if: steps.get_changed_files.outputs.any_changed == 'true'
      run: |
        cd backend/app
        pylint --rcfile=.pylintrc ${{ steps.get_changed_files.outputs.all_changed_files }}
